<a href="https://colab.research.google.com/github/009vinaysharma/AWS-ML-Arya/blob/main/day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# File Handling in Python

## What is File Handling?

File Handling in Python is used to create, read, write, and modify files. It allows us to store data permanently instead of keeping it only in memory. Python provides built-in functions to work with files efficiently.

## Why File Handling?

- Store data permanently.
- Read and update existing data.
- Save user information, reports, and logs.
- Useful for applications that require data storage.

---

# Python File Modes

When using `open("filename.txt", "mode")`, you must specify a file mode.

| Mode | Action | Behavior if File Exists | Behavior if File is Missing |
|------|--------|--------------------------|-----------------------------|
| `r` | Read | Opens the file for reading | ❌ Error (`FileNotFoundError`) |
| `w` | Write | Overwrites existing content | ✅ Creates a new file |
| `a` | Append | Adds data at the end of the file | ✅ Creates a new file |
| `x` | Create | ❌ Error if file already exists | ✅ Creates a new file |
| `r+` | Read & Write | Opens for reading and writing | ❌ Error if file is missing |
| `w+` | Read & Write | Overwrites existing content | ✅ Creates a new file |
| `a+` | Read & Append | Appends data and allows reading | ✅ Creates a new file |

---

# Common File Methods

- `read()` → Reads the entire file.
- `readline()` → Reads one line at a time.
- `readlines()` → Reads all lines and returns a list.
- `write()` → Writes data into a file.
- `writelines()` → Writes multiple lines.
- `close()` → Closes the file.

---

# Syntax

```python
file = open("filename.txt", "mode")

# Perform operations

file.close()
```

It is recommended to use `with open()` because it automatically closes the file after completing the operation.

Example:

```python
with open("sample.txt", "r") as file:
    content = file.read()
    print(content)
```

---

# Example

The following example demonstrates how to:

1. Create a text file.
2. Write data into the file.
3. Read the contents of the file.
4. Append new data.
5. Read the updated file.

This example helps understand the basic operations of Python File Handling.

---

# Conclusion

File Handling is an important feature of Python that allows data to be stored and managed permanently. Using different file modes (`r`, `w`, `a`, `x`, etc.), we can read, write, append, and update files easily. For safer file operations, using `with open()` is the recommended approach because it automatically closes the file after use.

In [ ]:
from google.colab import drive
# drive.mount('/content/drive')
data = open("/content/drive/MyDrive/hello.txt","r")
data.read()


'we are Indians'

In [ ]:
data = open("/content/drive/MyDrive/file1.csv","r")
data.read()

'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [ ]:
# file handling example
# creating and writing to a file
data1 = open("/content/drive/MyDrive/hello.txt","w")
data1.write("we are aryans")

data1 = open("/content/drive/MyDrive/hello.txt","r")
data1.read()


'we are aryansre my Brothers\n'

In [ ]:
data2 = open("/content/drive/MyDrive/hello.txt","w")
data2.write("we are Indians")

data2 = open("/content/drive/MyDrive/hello.txt","r")
data2.read()

'we are Indians'

In [ ]:
data1 = open("/content/drive/MyDrive/hello.txt","r")
data1.read()

data1 = open("/content/drive/MyDrive/hello.txt", "a")
data1.write("All Indians are my Brothers\n")

data1 = open("/content/drive/MyDrive/hello.txt","r")
data1.read()

'we are aryansre my Brothers\nAll Indians are my Brothers\n'

In [ ]:
data = open("/content/drive/MyDrive/file1.csv", "r")

print(data.read())

data.close()

name,roll no
dheeraj,123
kunal,1234
abhishek,12345
praveen,12356
anjali,1234567


In [ ]:
data = open("/content/drive/MyDrive/file1.csv", "a")

data.write("\n101, Vinay Sharma, CSE(AI), Jaipur")

data.close()

print("New record added successfully.")

New record added successfully.


In [ ]:
data = open("/content/drive/MyDrive/file1.csv", "r")

print(data.read())

data.close()

name,roll no
dheeraj,123
kunal,1234
abhishek,12345
praveen,12356
anjali,1234567
101, Vinay Sharma, CSE(AI), Jaipur


In [ ]:
data = open("/content/drive/MyDrive/file1.csv", "w")

data.write("ID,Name,Course,City\n")
data.write("101,Vinay Sharma,CSE(AI),Jaipur\n")
data.write("102,Rahul,CSE,Delhi")

data.close()

print("CSV file overwritten successfully.")

CSV file overwritten successfully.


In [ ]:
data = open("/content/drive/MyDrive/file1.csv", "r")

print(data.read())

data.close()

ID,Name,Course,City
101,Vinay Sharma,CSE(AI),Jaipur
102,Rahul,CSE,Delhi


In [ ]:
# Append a new row to CSV file

data = open("/content/drive/MyDrive/file1.csv", "a")

data.write("\n103,Rohit,CSE(AI),Jaipur")

data.close()

print("New record appended successfully.")

New record appended successfully.


In [ ]:
data = open("/content/drive/MyDrive/file1.csv", "r")

print(data.read())

data.close()

ID,Name,Course,City
101,Vinay Sharma,CSE(AI),Jaipur
102,Rahul,CSE,Delhi
103,Rohit,CSE(AI),Jaipur


In [ ]:
#direct access without drive
data = open('hello.txt','r')
data.read()

'Hello File Handling..............'

# NumPy

## What is NumPy?

NumPy (Numerical Python) is a Python library used for numerical computations. It provides support for multi-dimensional arrays, matrices, and mathematical functions. NumPy is faster than Python lists because it is implemented in C.

### Features
- Fast array operations
- Multi-dimensional arrays
- Mathematical functions
- Linear algebra support
- Random number generation

### Installation

```python
pip install numpy
```

In [ ]:
import numpy as np

In [ ]:
l = [10,20,30,40]
l*2

[10, 20, 30, 40, 10, 20, 30, 40]

In [ ]:
#power of numpy
l = [10,20,30,40]
arr = np.array(l)
arr*2

array([20, 40, 60, 80])

In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr)
print(arr[0]+arr[1])
print(arr[0]+arr[2])
print(arr[0]+arr[3])
print(arr[1]+arr[0])
print(arr[1]+arr[1])
print(arr[1]+arr[2])
print(arr[1]+arr[3])
print(arr[2]+arr[0])
print(arr[2]+arr[1])
print(arr[2]+arr[2])
print(arr[2]+arr[3])
print(arr[0]+arr[1]+arr[2]+arr[3])



1
2
3
4
[1 2 3 4]
3
4
5
3
4
5
6
4
5
6
7
10


In [ ]:
import numpy as np

# Python List
l = [10, 20, 30, 40]

print(l)
print(type(l))

# Convert List to NumPy Array
arr = np.array(l)

print(arr)
print(type(arr))

[10, 20, 30, 40]
<class 'list'>
[10 20 30 40]
<class 'numpy.ndarray'>


In [ ]:
# change value
import numpy as np
l = [10,20,30,40]
l[0] = 100
l[-1] = 150
print(l)
# numpy
arr = np.array(l)
arr[0] = 200
arr[-1] = 250
print(arr)


[100, 20, 30, 150]
[200  20  30 250]


In [ ]:
# change value
import numpy as np
l = [10,20,30,40]
l[0] = 100
l[-1] = 150
print(l)
l.sort()
print(l)
# numpy
arr = np.array(l)
arr[0] = 200
arr[-1] = 250
print(arr)
arr.sort()
print(arr)


[100, 20, 30, 150]
[20, 30, 100, 150]
[200  30 100 250]
[ 30 100 200 250]


In [ ]:
# Add 2 to each element

import numpy as np

# Python List
l = [10, 20, 30, 40]

# print(l + 2)   # ❌ Error

# Convert list to NumPy array
arr = np.array(l)

# Add 2 to every element
print(arr + 2)

[12 22 32 42]


In [ ]:
#arange in numpy
import numpy as np
arr = np.arange(5)
print(arr)

arr = np.arange(1,15,2)
print(arr)

arr = np.arange(1,15,3)
print(arr)

arr = np.arange(1,15)
print(arr)

[0 1 2 3 4]
[ 1  3  5  7  9 11 13]
[ 1  4  7 10 13]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
# home work  same work on 2d and 3 d
# work on csv  use append write more actions

# 2D NumPy Array

A 2D (Two-Dimensional) array consists of rows and columns. It is similar to a matrix or a table.

In this example, a Python nested list is converted into a NumPy 2D array using `np.array()`.

import numpy as np

# 2D Python List
l = [[1,2,3],
     [4,5,6],
     [7,8,9]]

print(l)

# Convert into NumPy Array
arr = np.array(l)

print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)

In [ ]:
l = [[1,2,3],[4,5,6]]
print(l)
print(l[0][1])
print(l[1][2])
# 2D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0][1])
print(arr[1][2])


[[1, 2, 3], [4, 5, 6]]
2
6
[[1 2 3]
 [4 5 6]]
2
6


In [ ]:
# 2d example
l = [[1,2,3],[4,5,6],[7,8,9]]
print(l)

# 2D numpy
arr = np.array(l)
print(arr)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

# 2D Python List
l = [[1,2,3],
     [4,5,6],
     [7,8,9]]

print(l)

# Convert into NumPy Array
arr = np.array(l)

print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2
(3, 3)


In [ ]:
import numpy as np

# 3D Python List
l = [
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
]

print("Python List:")
print(l)

# Convert to NumPy Array
arr = np.array(l)

print("\nNumPy Array:")
print(arr)

print("\nDimensions :", arr.ndim)
print("Shape      :", arr.shape)
print("Size       :", arr.size)
print("Data Type  :", arr.dtype)

Python List:
[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

NumPy Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Dimensions : 3
Shape      : (2, 2, 3)
Size       : 12
Data Type  : int64


In [ ]:
l = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
print(l)

#3D array
arr = np.array(l)
print(arr)
print('dimensions',arr.ndim)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
dimensions 3


#Example of multi with list and array

+ time comparsion
+ zeros (3,4)
+ ones (2,3)
+ full ((2,2),7)
+ random (2,3)
+ arange (0,10,2)

Array properties

+ shape
+ dimension | direction
+ size
+ dtype

Array Reshaping

+ reshape()
+ flatten() -> create copy | shallow copy
+ ravel() -> return original | deep copy
+ transpose -> .T -> reverse

In [ ]:
import numpy as np

arr = np.arange(1,100)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [ ]:
import numpy as np

matrix = np.random.randint(1, 10, size=(3, 3))
print(matrix)

[[5 9 6]
 [6 9 1]
 [1 5 7]]


In [ ]:
import numpy as np
matrix = np.random.randint(1,100, size=(9,4))
print(matrix)

[[39 94 26 86]
 [74 79  3 28]
 [38 86 59 85]
 [29 68 37 22]
 [95 37 54 44]
 [ 9 59 91 91]
 [68 33 73 11]
 [57  7 47 92]
 [31 82 82 58]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Array:")
print(arr)

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64


In [ ]:
import numpy as np
import time

# For List
start = time.time()

sum1 = 0
for i in range(1000000):
    sum1 += i * 2

end = time.time()

print("For List", sum1, end - start)


# For NumPy Array
start1 = time.time()

arr = np.arange(1000000) * 2
sum2 = arr.sum()

end1 = time.time()

print("For Array", sum2, end1 - start1)

For List 999999000000 0.1625373363494873
For Array 999999000000 0.0060918331146240234


In [ ]:
import numpy as np
import time as t

#for list
start = t.time()

sum1 = 0

for i in range(1,100000):
  sum1 += i*2

end = t.time()

print("for list",sum1,end - start)

#for Numpy array
start1 = t.time()
arr = np.arange(1,100000)*2

sum2 = arr.sum()

end1 = t.time()

print("for array",sum2,end1 - start1)


for list 9999900000 0.01116943359375
for array 9999900000 0.0009319782257080078


In [ ]:
import time as t
print(t.time())

1781857921.5046244


In [ ]:
import numpy as np

# array 1 d
arr = np.zeros(5)
print(arr)

# array 2 d
arr = np.zeros((2,3))
print(arr)

# array 3 d
arr = np.zeros((2,3,4))
print(arr)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
import numpy as np

# array 1d
arr = np.ones(5)
print(arr)

# array 2d
arr = np.ones((2,3))
print(arr)

# array 3d
arr = np.ones((2,3,4))
print(arr)


[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
# 1D
arr = np.zeros(5)
print(arr)
print(arr.shape)   # (5,)
print(arr.ndim)    # 1
print(arr.size)    # 5
print(arr.dtype)   # float64

# 2D
print("2D zeros starts")
arr1 = np.zeros((3,2))
print(arr1)
print(arr1.shape)  # (3,2)
print(arr1.ndim)   # 2
print(arr1.size)   # 6
print(arr1.dtype)  # float64

[0. 0. 0. 0. 0.]
(5,)
1
5
float64
2D zeros starts
[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2)
2
6
float64


In [ ]:
# 1D
arr = np.ones(5)
print(arr)
print(arr.shape)   # (5,)
print(arr.ndim)    # 1
print(arr.size)    # 5
print(arr.dtype)   # float64

# 2D
print("2D ones starts")
arr1 = np.ones((3,2))
print(arr1)
print(arr1.shape)  # (3,2)
print(arr1.ndim)   # 2
print(arr1.size)   # 6
print(arr1.dtype)  # float64

[1. 1. 1. 1. 1.]
(5,)
1
5
float64
2D ones starts
[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2)
2
6
float64


In [ ]:
# 1D
arr = np.full(5, 7)
print(arr)
print(arr.shape)   # (5,)
print(arr.ndim)    # 1
print(arr.size)    # 5
print(arr.dtype)   # int64

# 2D
print("2D full starts")
arr1 = np.full((3,2), 7)
print(arr1)
print(arr1.shape)  # (3,2)
print(arr1.ndim)   # 2
print(arr1.size)   # 6
print(arr1.dtype)  # int64

[7 7 7 7 7]
(5,)
1
5
int64
2D full starts
[[7 7]
 [7 7]
 [7 7]]
(3, 2)
2
6
int64


In [ ]:
import numpy as np
# 1d array
arr = np.arange(6)
print(arr)

#2d array
arr1 = arr.reshape(2,3)
print(arr1)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [ ]:
# flatten
import numpy as np
#2d
arr = np.arange(6)
arr1 = arr.reshape(2,3)
print(arr1)

# flatten
print(arr1.flatten())

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [ ]:
# flatten
import numpy as np
#2d
arr = np.arange(6)
arr1 = arr.reshape(2,3)
print(arr1)

# flatten
arr_new = arr1.flatten()
arr_new[0] = 100
print(arr_new)


[[0 1 2]
 [3 4 5]]
[100   1   2   3   4   5]


In [ ]:
# ravel
import numpy as np
#2d
arr = np.arange(9)
arr1 = arr.reshape(3,3)
print(arr1)

#ravel
arr_new = arr.ravel()
arr_new[0] = 100
print(arr1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[100   1   2]
 [  3   4   5]
 [  6   7   8]]


In [ ]:
# transpose
import numpy as np

arr = np.arange(9).reshape(3,3)
print(arr)

# transpose()
arr1 = arr.transpose()
print(arr1)

# .T
arr1 = arr.T
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


# Array Slicing

Array slicing ka use array ke kisi specific part ko access karne ke liye kiya jata hai.

## Syntax

```python
array[start : stop : step]
```

- **start** → Starting index (included)
- **stop** → Ending index (excluded)
- **step** → Gap between elements

### Examples

```python
arr[1:5]
arr[:4]
arr[::2]
```

In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

print(arr[1:5])
print(arr[:4])
print(arr[::2])

[20 30 40 50]
[10 20 30 40]
[10 30 50]


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5],
                [4,5,6,7,8]])

print(arr[1, 1:4])

print(arr[0:2])

print(arr[0:2, 0])

print(arr[0:2, 3])

print(arr[0:2, 1:2])

[5 6 7]
[[1 2 3 4 5]
 [4 5 6 7 8]]
[1 4]
[4 7]
[[2]
 [5]]


In [ ]:
import numpy as np
arr = np.array([[10,20],[30,40]])

print(arr[0:1,0:1])
print(arr[1:2,1:2])
print(arr[0:1:2])
print(arr[1:2:2])
print(arr[0:2, 0])
print(arr[0:2, 1])
print(arr[0:2, 1:2])
print(arr[0:2, :2])

[[10]]
[[40]]
[[10 20]]
[[30 40]]
[10 30]
[20 40]
[[20]
 [40]]
20 30
[[10 20]
 [30 40]]
[[10 20]
 [30 40]]


In [ ]:
# array slicing for 3d
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0, 1, 2])
print(arr[1, 1, 2])
print(arr[1, 0, 2])
print(arr[0:2, 0, 2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
12
9
[3 9]


In [ ]:
import numpy as np

arr = np.array([
    [2453,   75, 183975],
    [5795,   99, 573705],
    [4100,   36, 147600],
    [7526,   86, 647236],
    [9528,   45, 428760],
    [10788,  17, 183396]
])

print(arr[:3])  # first 3 rows

print(arr[-3:]) # last 3 rows

print(arr[:, 0]) # first column

print(arr[2:4])
print(arr[1,1])
print(arr[0,2])
print(arr[4:,1])
print(arr[[1,0],[1,2]])



[[  2453     75 183975]
 [  5795     99 573705]
 [  4100     36 147600]]
[[  7526     86 647236]
 [  9528     45 428760]
 [ 10788     17 183396]]
[ 2453  5795  4100  7526  9528 10788]
[[  4100     36 147600]
 [  7526     86 647236]]
99
183975
[45 17]
[    99 183975]


In [ ]:
import numpy as np

arr = np.array([
    [2453,   75, 183975],
    [5795,   99, 573705],
    [4100,   36, 147600],
    [7526,   86, 647236],
    [9528,   45, 428760],
    [10788,  17, 183396]
])

print(arr[0, 0:2])

print(arr[[0,1], [2,1]])


print(arr[2:4])

print(arr[4:, 2])
print(arr[4:, 1])

[2453   75]
[183975     99]
[[  4100     36 147600]
 [  7526     86 647236]]
[428760 183396]
[45 17]


In [ ]:
# 3d
import numpy as np
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
    ])
print(arr.ndim) # 3d
print(arr[0])# block
print("=>>",arr[0,0]) #block row
print("=>>",arr[0,0,0]) #block row column
print('==>',arr[0,1,1])
print('==>',arr[1,0,1])

print(arr[:,0])   # all block row 0

print(arr[:,:,0]) # all block -> all rows -> cols 0


3
[[1 2]
 [3 4]]
=>> [1 2]
=>> 1
==> 4
==> 6
[[1 2]
 [5 6]]
[[1 3]
 [5 7]]


In [ ]:
#3d
import numpy as np
arr = np.array([
    [[1,2],
     [3,4]
    ],
    [[5,6],
     [7,8]
    ]
    ])
# print(arr.ndim) # 3d
# print("=>",arr[0]) # block
# print("=>>",arr[0,0]) # block -> row
# print("=>>>",arr[0,0,0]) # block -> row -> cols
#
print(arr[:,0]) # all block -> row -> 0
print(arr[:,:,0]) # all block -> all rows -> cols 0

[[1 2]
 [5 6]]
[[1 3]
 [5 7]]


# For Loop in numpy

For loop ka use array ke har element ko access karne ke liye kiya jata hai.

```python
for i in arr:
    print(i)
```

In [ ]:
import numpy as np
#1d
arr = np.array([10,20,30,40,50,60])
print(arr)
for i in arr:
    print(i)

[10 20 30 40 50 60]
10
20
30
40
50
60


In [ ]:
#2d
import numpy as np

arr = np.array([[10,20],[30,40],[50,60]])
for i in arr:
  print(i)

[10 20]
[30 40]
[50 60]


In [ ]:
#2d
import numpy as np

arr = np.array([[10,20],[30,40],[50,60]])
print(arr)
for i in arr:

  for j in i:
    print(j)

[[10 20]
 [30 40]
 [50 60]]
10
20
30
40
50
60


In [ ]:
#3d
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
  print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
#3d
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
  for j in i:
    print(j)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [ ]:
#3d
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70])

for i in arr < 50:
    print(i)

True
True
True
True
False
False
False


In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70])

for i in range(len(arr)):
    if arr[i] < 50:
        arr[i] += 100
    else:
        arr[i] += 50

print(arr)
print(np.sort(arr))

[110 120 130 140 100 110 120]
[100 110 110 120 120 130 140]


# While Loop

While loop condition true hone tak execute hota hai.

```python
while condition:
```

In [ ]:
# 1d in while loop
import numpy as np
arr = np.array([10,20,30,40,50,60])
while i < len(arr):
  print(arr[i])
  i+=1

30
40
50
60


In [ ]:
#2d
import numpy as np

arr=np.array([[10,20,30,40],[50,60,70,80]])

i=0

while i<len(arr):
  j=0 # Initialize j for each row
  while j<len(arr[i]):
    print(arr[i,j]) # Correctly access elements with arr[i,j]
    j+=1
  i+=1 # Increment i for the next row

10
20
30
40
50
60
70
80


In [ ]:
#3d
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
i = 0
while i<len(arr):
  j=0
  while j<len(arr[i]):
    k=0
    while k<len(arr[i,j]):
      print(arr[i,j,k])
      k+=1
    j+=1
  i+=1


1
2
3
4
5
6
7
8
9
10
11
12


# np.nditer()

`np.nditer()` multi-dimensional arrays ko efficiently iterate karne ke liye use hota hai.

```python
for i in np.nditer(arr):
    print(i)
```

In [ ]:
import numpy as np

arr=np.array([[1,2],[3,4]])

for i in np.nditer(arr):
    print(i)

1
2
3
4


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [ ]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Sorting

Sorting elements ko ascending order me arrange karta hai.

```python
np.sort(arr)
```

2D Arrays

- axis=0 → Column wise
- axis=1 → Row wise

In [ ]:
#sorting
#1d

import numpy as np
arr = np.array([12,34,56,3,2,7,8])
print(np.sort(arr))#accending
print(np.sort(arr)[::-1])#decending


[ 2  3  7  8 12 34 56]
[56 34 12  8  7  3  2]


In [ ]:
#2d
import numpy as np
arr = np.array([[123,43,55,12],[30,20,14,56]])
print(np.sort(arr))#accending


[[ 12  43  55 123]
 [ 14  20  30  56]]
[[ 14  20  30  56]
 [ 12  43  55 123]]


In [ ]:
import numpy as np

arr=np.array([5,2,8,1])

print(np.sort(arr))

arr2=np.array([[5,2],[8,1]])

print(np.sort(arr2,axis=0))
print(np.sort(arr2,axis=1))

[1 2 5 8]
[[5 1]
 [8 2]]
[[2 5]
 [1 8]]


# Filtering

Filtering condition ke basis par values select karta hai.

```python
arr[arr>2]
```

In [ ]:
# filter 1d
import numpy as np
arr - np.array([10,20,30,40])
print(arr[0:3])

[5 2 8]


In [ ]:
# filter 1d
import numpy as np
arr = np.array([10,20,30,40])
print(arr[arr>20])

[30 40]


In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])

print(arr[arr>2])


[3 4 5]


In [7]:
import numpy as np
arr = np.array([10,100,20,30,40])
arr_f = arr[arr > 20]
print(arr_f)

[100  30  40]


In [9]:
import numpy as np
arr = np.array([10,100,20,30,40])
arr_f = arr[arr != 20]
print(arr_f)

[ 10 100  30  40]


In [15]:
import numpy as np
arr = np.array([10,15,20,19,30])
arr_f = arr[(arr > 10) & (arr < 20)]
print(arr_f)

[15 19]


In [16]:
import numpy as np
arr = np.array([10,15,20,19,30])
arr_f = arr[(arr != 10) & (arr != 20)]
print(arr_f)

[15 19 30]
