<a href="https://colab.research.google.com/github/009vinaysharma/AWS-ML-Arya/blob/main/day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fancy Indexing

Fancy Indexing NumPy ka ek advanced indexing method hai jisme hum **list ya array of indices** ka use karke multiple elements ko ek saath access karte hain.

### Syntax

```python
array[[index1, index2, index3]]
```

### 2D Syntax

```python
array[[row1, row2], [col1, col2]]
```

Yeh pair-wise indexing karta hai.

```
array[[0,1],[2,1]]

↓

array[0,2]
array[1,1]
```

### Uses

- Multiple elements ko ek saath access karna
- Specific rows select karna
- Specific columns select karna
- Random indexing

In [2]:
# fancy indexing
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr)
arr_f = arr[[0,2]] # 0 index value, 2 index value
print(arr_f)

[10 20 30 40 50 60]
[10 30]


In [5]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

print(arr[[0,2,5]])


[10 30 60]


In [9]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

arr_f = arr[[0,2],[1,2]]
arr_f1 = arr[[0,1],[2,2]]
print(arr_f)
print(arr_f1)

[20 90]
[30 60]


In [14]:
import numpy as np
# selecting multiple rows
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr[[0,2]])

# selecting multiple columns
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr[:, [0,2]])

[[10 20 30]
 [70 80 90]]
[[10 30]
 [40 60]
 [70 90]]


# np.where() Condition

`np.where()` NumPy ka ek function hai jo condition ke basis par values ya indices return karta hai.

## Syntax

```python
np.where(condition)
```

Returns the index positions where the condition is **True**.

### Syntax (Ternary Operator)

```python
np.where(condition, value_if_true, value_if_false)
```

- **condition** → Check ki jane wali condition
- **value_if_true** → Agar condition True ho
- **value_if_false** → Agar condition False ho

## Uses

- Find indices
- Replace values
- Apply conditions on arrays

In [4]:
# where
import numpy as np
arr = np.array([10,20,3,4,90,100])
print(arr)
arr_w = np.where(arr > 9,'True','False')
print(arr_w)

[ 10  20   3   4  90 100]
['True' 'True' 'False' 'False' 'True' 'True']


In [10]:
arr = np.array([5,6,7,8,11,24,16,19,25])
print(arr)
arr_w = np.where((arr>10) & (arr<20),arr*2,arr+2)
print(arr_w)



[ 5  6  7  8 11 24 16 19 25]
[ 7  8  9 10 22 26 32 38 27]


In [15]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(np.where(arr > 25))

(array([2, 3, 4]),)


In [16]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(np.where(arr > 25, arr+100, arr))

[ 10  20 130 140 150]


In [17]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(np.where(arr > 25, "True", "False"))

['False' 'False' 'True' 'True' 'True']


In [18]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

print(np.where(arr % 2 == 0, "Even", "Odd"))

['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']


In [19]:
import numpy as np

arr = np.array([-10,20,-30,40,-50])

print(np.where(arr < 0, -arr, arr))

[10 20 30 40 50]


# Adding and Removing Data in NumPy

NumPy provides functions to add (join) and remove elements, rows, and columns from arrays.

## 1. Concatenate

Used to join two arrays.

```python
np.concatenate((arr1, arr2))
```

---

## 2. Add Row

Used to add a new row to a 2D array.

```python
np.vstack((original, new_row))
```

---

## 3. Add Column

Used to add a new column to a 2D array.

```python
np.hstack((original, new_col))
```

---

## 4. Delete Element

Used to remove an element from a 1D array or a row/column from a 2D array.

```python
np.delete(array, index)
```

In [22]:
# concatinate 1d
import numpy as np

arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

arr_arr2 = np.concatenate((arr1, arr2))

print(arr_arr2)

[10 20 30 40 50 60]


In [28]:
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

arr_arr2 = np.array((arr1+arr2))

print('add withoe use concatenate:->',arr_arr2)

l1 = [10,20,30]
l2 = [40,50,60]
l3 = l1+l2
print('add list:->',l3)

arr_arr3 = np.concatenate((arr1, arr2))

print('use concatenate:->',arr_arr3)

add withoe use concatenate:-> [50 70 90]
add list:-> [10, 20, 30, 40, 50, 60]
use concatenate:-> [10 20 30 40 50 60]


In [21]:
# concatinate 2d
import numpy as np

arr1 = np.array([[10,20],
                 [30,40]])

arr2 = np.array([[50,60],
                 [70,80]])


arr_arr2 = np.concatenate((arr1, arr2))

print(arr_arr2)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [29]:
import numpy as np

arr1 = np.array([[10,20],
                 [30,40]])

arr2 = np.array([[50,60],
                 [70,80]])

# Concatenate row-wise (axis=0)
arr_arr2 = np.concatenate((arr1, arr2), axis=0)

print(arr_arr2)

#  Concatenate column-wise (axis=1)
arr_arr_2 = np.concatenate((arr1, arr2), axis=1)

print(arr_arr_2)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
[[10 20 50 60]
 [30 40 70 80]]


In [33]:
# 3d concatenate
import numpy as np

arr1 = np.array([
    [[1,2],[3,4]]
])

arr2 = np.array([
    [[5,6],[7,8]]
])

result = np.concatenate((arr1, arr2))

print(result)




[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
# 3d concatenate
import numpy as np

arr1 = np.array([
    [[1,2],[3,4]]
])

arr2 = np.array([
    [[5,6],[7,8]]
])

# concatenate row-wise (axis = 0)
result_row = np.concatenate((arr1, arr2), axis=0)

print(result_row)

# concatenate column-wise (axis = 1)
result_col = np.concatenate((arr1, arr2), axis=1)

print(result_col)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [35]:
# 3D Concatenate
import numpy as np

arr1 = np.array([
    [[1,2],
     [3,4]]
])

arr2 = np.array([
    [[5,6],
     [7,8]]
])

# axis = 0 (Depth/Block Wise)
result0 = np.concatenate((arr1, arr2), axis=0)
print("Axis = 0")
print(result0)

# axis = 1 (Row Wise)
result1 = np.concatenate((arr1, arr2), axis=1)
print("\nAxis = 1")
print(result1)

# axis = 2 (Column Wise)
result2 = np.concatenate((arr1, arr2), axis=2)
print("\nAxis = 2")
print(result2)

Axis = 0
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Axis = 1
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]

Axis = 2
[[[1 2 5 6]
  [3 4 7 8]]]


In [38]:
# v-stack
import numpy as np

arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

arr_arr2 = np.vstack((arr1, arr2))

print(arr_arr2)

[[10 20 30]
 [40 50 60]]


In [37]:
# v-stack
import numpy as np

arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

arr_arr2 = np.vstack((arr1, arr2))

print(arr_arr2)

arr_22 = np.concatenate((arr1, arr2))

print(arr_22)

[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]


In [41]:
import numpy as np

arr1 = np.array([
    [1,2],
    [3,4]
])

arr2 = np.array([
    [5,6],
    [7,8]
])

result = np.vstack((arr1, arr2))

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [44]:
import numpy as np

arr1 = np.array([
    [[1,2],
     [3,4]],[[7,8],[9,10]]
])

arr2 = np.array([
    [[11,12],
     [13,14]],[[15,16],[17,18]]
])

result = np.vstack((arr1, arr2))

print(result)

[[[ 1  2]
  [ 3  4]]

 [[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]


In [40]:
# hstack
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])

arr_arr_2 = np.hstack((arr1, arr2))

print(arr_arr_2)


[10 20 30 40 50 60]


In [42]:
import numpy as np

arr1 = np.array([
    [1,2],
    [3,4]
])

arr2 = np.array([
    [5,6],
    [7,8]
])

result = np.hstack((arr1, arr2))

print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [45]:
import numpy as np

arr1 = np.array([
    [[1,2],
     [3,4]],[[7,8],[9,10]]
])

arr2 = np.array([
    [[11,12],
     [13,14]],[[15,16],[17,18]]
])

result = np.hstack((arr1, arr2))

print(result)

[[[ 1  2]
  [ 3  4]
  [11 12]
  [13 14]]

 [[ 7  8]
  [ 9 10]
  [15 16]
  [17 18]]]


# Statistical Functions in NumPy

Statistical functions are used to perform mathematical and statistical calculations on NumPy arrays.

## Functions

### 1. np.sum()
Returns the sum of all elements.

### 2. np.mean()
Returns the average of all elements.

**Formula:**
Mean = Sum of Elements / Number of Elements

### 3. np.median()
Returns the middle value after sorting the data.

### 4. np.mode()
Returns the most frequently occurring value.
(NumPy has no direct `mode()` function. It is available in `scipy.stats`.)

### 5. np.min()
Returns the smallest element.

### 6. np.max()
Returns the largest element.

### 7. np.var()
Returns the variance of the data.

### 8. np.std()
Returns the standard deviation.

### 9. np.prod()
Returns the product of all elements.

### 10. np.cumsum()
Returns the cumulative (running) sum.

### 11. np.cumprod()
Returns the cumulative (running) product.

### 12. np.argmin()
Returns the index of the minimum value.

### 13. np.argmax()
Returns the index of the maximum value.

### 14. np.abs()
Returns the absolute value.

### 15. np.unique()
Returns only unique elements.

### 16. np.percentile()
Returns the value at a given percentile.

### 17. np.quantile()
Returns the value at a given quantile.

### 18. np.ptp()
Returns the range (Maximum − Minimum).

### 19. np.any()
Returns True if at least one element is True.

In [65]:
import numpy as np

arr = np.array([10,20,30,40,50,50])

print('Sum :',np.sum(arr))  #sum
print('Mean :',np.mean(arr)) #mean
print('Median :',np.median(arr)) #median
print("Mode :",stats.mode(arr).mode) # mode
print('Min :',np.min(arr)) #min
print('Max :',np.max(arr)) #max
print('Variance :',np.var(arr)) #variance
print('Standard Deviation :',np.std(arr)) #standard deviation
print('Product :',np.prod(arr)) #product
print('Cumulative Sum :',np.cumsum(arr)) #cumulative sum
print('Cumulative Product :',np.cumprod(arr)) #cumulative product
print('ArgMin :',np.argmin(arr)) #argument minimum
print('ArgMax :',np.argmax(arr)) #argument maximum
print('Absolute :',np.abs(arr)) #absolute
print('Unique :',np.unique(arr)) #unique
print('50th Percentile :',np.percentile(arr,50)) #50th percentile
print('0.5 Quantile :',np.quantile(arr,0.5)) #0.5 quantile
print("Range :", np.ptp(arr)) #range
arr3 = np.array([-5,-10,15,-20])
print("Range :", np.ptp(arr3))  #range

Sum : 200
Mean : 33.333333333333336
Median : 35.0
Mode : 50
Min : 10
Max : 50
Variance : 222.22222222222226
Standard Deviation : 14.9071198499986
Product : 600000000
Cumulative Sum : [ 10  30  60 100 150 200]
Cumulative Product : [       10       200      6000    240000  12000000 600000000]
ArgMin : 0
ArgMax : 4
Absolute : [10 20 30 40 50 50]
Unique : [10 20 30 40 50]
50th Percentile : 35.0
0.5 Quantile : 35.0
Range : 40
Range : 35


In [46]:
import numpy as np
from scipy import stats

arr = np.array([2,4,6,8,10])

print("Array :", arr)

print("Sum :", np.sum(arr))
print("Mean :", np.mean(arr))
print("Median :", np.median(arr))

# Mode
arr2 = np.array([2,2,3,4,4,4,5])
mode = stats.mode(arr2)

print("Mode :", mode.mode)
print("Frequency :", mode.count)

print("Minimum :", np.min(arr))
print("Maximum :", np.max(arr))
print("Variance :", np.var(arr))
print("Standard Deviation :", np.std(arr))
print("Product :", np.prod(arr))
print("Cumulative Sum :", np.cumsum(arr))
print("Cumulative Product :", np.cumprod(arr))
print("ArgMin :", np.argmin(arr))
print("ArgMax :", np.argmax(arr))

arr3 = np.array([-5,-10,15,-20])

print("Absolute :", np.abs(arr3))

arr4 = np.array([1,2,2,3,3,4,5])

print("Unique :", np.unique(arr4))
print("50th Percentile :", np.percentile(arr,50))
print("0.5 Quantile :", np.quantile(arr,0.5))
print("Range :", np.ptp(arr))

bool_arr = np.array([False,False,True])

print("Any :", np.any(bool_arr))

Array : [ 2  4  6  8 10]
Sum : 30
Mean : 6.0
Median : 6.0
Mode : 4
Frequency : 3
Minimum : 2
Maximum : 10
Variance : 8.0
Standard Deviation : 2.8284271247461903
Product : 3840
Cumulative Sum : [ 2  6 12 20 30]
Cumulative Product : [   2    8   48  384 3840]
ArgMin : 0
ArgMax : 4
Absolute : [ 5 10 15 20]
Unique : [1 2 3 4 5]
50th Percentile : 6.0
0.5 Quantile : 6.0
Range : 8
Any : True


In [67]:
import numpy as np
from scipy import stats

arr = np.array([2,2,3,4,4,4,5])

result = stats.mode(arr)

print("Mode :", result.mode)
print("Frequency :", result.count)

Mode : 4
Frequency : 3


# Handling Missing Values

Missing values are the data values that are not available or are empty.

In NumPy, missing values are generally represented using:

- `np.nan` (Not a Number)

## Common Methods

1. Detect Missing Values
```python
np.isnan()
```

2. Replace Missing Values
```python
np.nan_to_num()
```

3. Calculate Mean Ignoring Missing Values
```python
np.nanmean()
```

4. Calculate Sum Ignoring Missing Values
```python
np.nansum()
```

5. Calculate Maximum Ignoring Missing Values
```python
np.nanmax()
```

6. Calculate Minimum Ignoring Missing Values
```python
np.nanmin()
```

# Handling Missing Values

Missing values are values that are not available in a dataset.
In NumPy, missing values are represented using **np.nan (Not a Number)**.

## Methods

- `np.isnan()` → Check missing values
- `np.nan_to_num()` → Replace missing values
- `np.nanmean()` → Mean ignoring missing values
- `np.nansum()` → Sum ignoring missing values
- `np.nanmax()` → Maximum ignoring missing values
- `np.nanmin()` → Minimum ignoring missing values

In [70]:
import numpy as np

arr = np.array([10,20,np.nan,40,50])

print(arr)

print(np.isnan(arr))

print(np.nan_to_num(arr, nan=0))

[10. 20. nan 40. 50.]
[False False  True False False]
[10. 20.  0. 40. 50.]


In [76]:
import numpy as np
#mean ignoring mising values
arr = np.array([10,20,np.nan,40,50])

print(np.nanmean(arr))

30.0


In [75]:
import numpy as np
# sum ignoring missing values
arr = np.array([10,20,np.nan,40,50])

print(np.nansum(arr))

120.0


In [74]:
import numpy as np

arr = np.array([10,20,np.nan,40,50])
# Maximum & Minimum Ignoring Missing Values
print("Maximum :", np.nanmax(arr))
print("Minimum :", np.nanmin(arr))

Maximum : 50.0
Minimum : 10.0


In [77]:
import numpy as np

# Creating array with missing values
arr = np.array([10,20,np.nan,40,50,np.nan,70])

print("Original Array :")
print(arr)

# Check missing values
print("\nMissing Values (True = Missing)")
print(np.isnan(arr))

# Count missing values
print("\nTotal Missing Values :")
print(np.sum(np.isnan(arr)))

# Replace missing values with 0
print("\nReplace Missing Values with 0")
print(np.nan_to_num(arr, nan=0))

# Replace missing values with 100
print("\nReplace Missing Values with 100")
print(np.nan_to_num(arr, nan=100))

# Mean ignoring missing values
print("\nMean :", np.nanmean(arr))

# Sum ignoring missing values
print("Sum :", np.nansum(arr))

# Maximum ignoring missing values
print("Maximum :", np.nanmax(arr))

# Minimum ignoring missing values
print("Minimum :", np.nanmin(arr))

Original Array :
[10. 20. nan 40. 50. nan 70.]

Missing Values (True = Missing)
[False False  True False False  True False]

Total Missing Values :
2

Replace Missing Values with 0
[10. 20.  0. 40. 50.  0. 70.]

Replace Missing Values with 100
[ 10.  20. 100.  40.  50. 100.  70.]

Mean : 38.0
Sum : 190.0
Maximum : 70.0
Minimum : 10.0


In [96]:
# Questionn
import numpy as np

# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],   # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],   # Beijing Bites
    [3, 200000, 230000, 260000, 300000],   # Pizza Hub
    [4, 180000, 210000, 240000, 270000],   # Burger Point
    [5, 160000, 185000, 205000, 230000]    # Chai Point
])

print(sales_data)

print(sales_data.shape) # shape of the array

print(sales_data.ndim) # dimension of the array

print(sales_data.size) # size of the array

print(sales_data[:, 0])

print('2021 sales data :',sales_data[:, 1])

print('2024 sales data :',sales_data[:, 4])

print("Maximum Sales Value :", sales_data.max())# max sales value
print(np.min(sales_data[:,1:]))# min sales value
print(np.sum(sales_data[:,1])) #total number of students in 2021

print(np.mean(sales_data[:,4])) #average sales in 2024.

print(np.sum(sales_data[:,1:], axis=1)) #total sales of each restaurant.
print(np.mean(sales_data[:,1:], axis=1)) #average sales of each restaurant




[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
(5, 5)
2
25
[1 2 3 4 5]
2021 sales data : [150000 120000 200000 180000 160000]
2024 sales data : [250000 190000 300000 270000 230000]
Maximum Sales Value : 300000
120000
810000
248000.0
[800000 610000 990000 900000 780000]
[200000. 152500. 247500. 225000. 195000.]
