<a href="https://colab.research.google.com/github/009vinaysharma/AWS-ML-Arya/blob/main/day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# File Handling in Python

## What is File Handling?

File Handling in Python is used to create, read, write, and modify files. It allows us to store data permanently instead of keeping it only in memory. Python provides built-in functions to work with files efficiently.

## Why File Handling?

- Store data permanently.
- Read and update existing data.
- Save user information, reports, and logs.
- Useful for applications that require data storage.

---

# Python File Modes

When using `open("filename.txt", "mode")`, you must specify a file mode.

| Mode | Action | Behavior if File Exists | Behavior if File is Missing |
|------|--------|--------------------------|-----------------------------|
| `r` | Read | Opens the file for reading | ❌ Error (`FileNotFoundError`) |
| `w` | Write | Overwrites existing content | ✅ Creates a new file |
| `a` | Append | Adds data at the end of the file | ✅ Creates a new file |
| `x` | Create | ❌ Error if file already exists | ✅ Creates a new file |
| `r+` | Read & Write | Opens for reading and writing | ❌ Error if file is missing |
| `w+` | Read & Write | Overwrites existing content | ✅ Creates a new file |
| `a+` | Read & Append | Appends data and allows reading | ✅ Creates a new file |

---

# Common File Methods

- `read()` → Reads the entire file.
- `readline()` → Reads one line at a time.
- `readlines()` → Reads all lines and returns a list.
- `write()` → Writes data into a file.
- `writelines()` → Writes multiple lines.
- `close()` → Closes the file.

---

# Syntax

```python
file = open("filename.txt", "mode")

# Perform operations

file.close()
```

It is recommended to use `with open()` because it automatically closes the file after completing the operation.

Example:

```python
with open("sample.txt", "r") as file:
    content = file.read()
    print(content)
```

---

# Example

The following example demonstrates how to:

1. Create a text file.
2. Write data into the file.
3. Read the contents of the file.
4. Append new data.
5. Read the updated file.

This example helps understand the basic operations of Python File Handling.

---

# Conclusion

File Handling is an important feature of Python that allows data to be stored and managed permanently. Using different file modes (`r`, `w`, `a`, `x`, etc.), we can read, write, append, and update files easily. For safer file operations, using `with open()` is the recommended approach because it automatically closes the file after use.

In [29]:
from google.colab import drive
# drive.mount('/content/drive')
data = open("/content/drive/MyDrive/hello.txt","r")
data.read()


'we are Indians'

In [33]:
data = open("/content/drive/MyDrive/file1.csv","r")
data.read()

'name,roll no\ndheeraj,123\nkunal,1234\nabhishek,12345\npraveen,12356\nanjali,1234567'

In [40]:
# file handling example
# creating and writing to a file
data1 = open("/content/drive/MyDrive/hello.txt","w")
data1.write("we are aryans")

data1 = open("/content/drive/MyDrive/hello.txt","r")
data1.read()


'we are aryansre my Brothers\n'

In [32]:
data2 = open("/content/drive/MyDrive/hello.txt","w")
data2.write("we are Indians")

data2 = open("/content/drive/MyDrive/hello.txt","r")
data2.read()

'we are Indians'

In [41]:
data1 = open("/content/drive/MyDrive/hello.txt","r")
data1.read()

data1 = open("/content/drive/MyDrive/hello.txt", "a")
data1.write("All Indians are my Brothers\n")

data1 = open("/content/drive/MyDrive/hello.txt","r")
data1.read()

'we are aryansre my Brothers\nAll Indians are my Brothers\n'

In [42]:
data = open("/content/drive/MyDrive/file1.csv", "r")

print(data.read())

data.close()

name,roll no
dheeraj,123
kunal,1234
abhishek,12345
praveen,12356
anjali,1234567


In [43]:
data = open("/content/drive/MyDrive/file1.csv", "a")

data.write("\n101, Vinay Sharma, CSE(AI), Jaipur")

data.close()

print("New record added successfully.")

New record added successfully.


In [44]:
data = open("/content/drive/MyDrive/file1.csv", "r")

print(data.read())

data.close()

name,roll no
dheeraj,123
kunal,1234
abhishek,12345
praveen,12356
anjali,1234567
101, Vinay Sharma, CSE(AI), Jaipur


In [45]:
data = open("/content/drive/MyDrive/file1.csv", "w")

data.write("ID,Name,Course,City\n")
data.write("101,Vinay Sharma,CSE(AI),Jaipur\n")
data.write("102,Rahul,CSE,Delhi")

data.close()

print("CSV file overwritten successfully.")

CSV file overwritten successfully.


In [46]:
data = open("/content/drive/MyDrive/file1.csv", "r")

print(data.read())

data.close()

ID,Name,Course,City
101,Vinay Sharma,CSE(AI),Jaipur
102,Rahul,CSE,Delhi


In [47]:
# Append a new row to CSV file

data = open("/content/drive/MyDrive/file1.csv", "a")

data.write("\n103,Rohit,CSE(AI),Jaipur")

data.close()

print("New record appended successfully.")

New record appended successfully.


In [49]:
data = open("/content/drive/MyDrive/file1.csv", "r")

print(data.read())

data.close()

ID,Name,Course,City
101,Vinay Sharma,CSE(AI),Jaipur
102,Rahul,CSE,Delhi
103,Rohit,CSE(AI),Jaipur


In [50]:
#direct access without drive
data = open('hello.txt','r')
data.read()

'Hello File Handling..............'

# NumPy

## What is NumPy?

NumPy (Numerical Python) is a Python library used for numerical computations. It provides support for multi-dimensional arrays, matrices, and mathematical functions. NumPy is faster than Python lists because it is implemented in C.

### Features
- Fast array operations
- Multi-dimensional arrays
- Mathematical functions
- Linear algebra support
- Random number generation

### Installation

```python
pip install numpy
```

In [51]:
import numpy as np

In [53]:
l = [10,20,30,40]
l*2

[10, 20, 30, 40, 10, 20, 30, 40]

In [57]:
#power of numpy
l = [10,20,30,40]
arr = np.array(l)
arr*2

array([20, 40, 60, 80])

In [66]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr)
print(arr[0]+arr[1])
print(arr[0]+arr[2])
print(arr[0]+arr[3])
print(arr[1]+arr[0])
print(arr[1]+arr[1])
print(arr[1]+arr[2])
print(arr[1]+arr[3])
print(arr[2]+arr[0])
print(arr[2]+arr[1])
print(arr[2]+arr[2])
print(arr[2]+arr[3])
print(arr[0]+arr[1]+arr[2]+arr[3])



1
2
3
4
[1 2 3 4]
3
4
5
3
4
5
6
4
5
6
7
10


In [67]:
import numpy as np

# Python List
l = [10, 20, 30, 40]

print(l)
print(type(l))

# Convert List to NumPy Array
arr = np.array(l)

print(arr)
print(type(arr))

[10, 20, 30, 40]
<class 'list'>
[10 20 30 40]
<class 'numpy.ndarray'>


In [70]:
# change value
import numpy as np
l = [10,20,30,40]
l[0] = 100
l[-1] = 150
print(l)
# numpy
arr = np.array(l)
arr[0] = 200
arr[-1] = 250
print(arr)


[100, 20, 30, 150]
[200  20  30 250]


In [71]:
# change value
import numpy as np
l = [10,20,30,40]
l[0] = 100
l[-1] = 150
print(l)
l.sort()
print(l)
# numpy
arr = np.array(l)
arr[0] = 200
arr[-1] = 250
print(arr)
arr.sort()
print(arr)


[100, 20, 30, 150]
[20, 30, 100, 150]
[200  30 100 250]
[ 30 100 200 250]


In [72]:
# Add 2 to each element

import numpy as np

# Python List
l = [10, 20, 30, 40]

# print(l + 2)   # ❌ Error

# Convert list to NumPy array
arr = np.array(l)

# Add 2 to every element
print(arr + 2)

[12 22 32 42]


In [75]:
#arange in numpy
import numpy as np
arr = np.arange(5)
print(arr)

arr = np.arange(1,15,2)
print(arr)

arr = np.arange(1,15,3)
print(arr)

arr = np.arange(1,15)
print(arr)

[0 1 2 3 4]
[ 1  3  5  7  9 11 13]
[ 1  4  7 10 13]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
# home work  same work on 2d and 3 d
# work on csv  use append write more actions

# 2D NumPy Array

A 2D (Two-Dimensional) array consists of rows and columns. It is similar to a matrix or a table.

In this example, a Python nested list is converted into a NumPy 2D array using `np.array()`.

In [80]:
l = [[1,2,3],[4,5,6]]
print(l)
print(l[0][1])
print(l[1][2])
# 2D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0][1])
print(arr[1][2])


[[1, 2, 3], [4, 5, 6]]
2
6
[[1 2 3]
 [4 5 6]]
2
6


In [84]:
# 2d example
l = [[1,2,3],[4,5,6],[7,8,9]]
print(l)

# 2D numpy
arr = np.array(l)
print(arr)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
import numpy as np

# 2D Python List
l = [[1,2,3],
     [4,5,6],
     [7,8,9]]

print(l)

# Convert into NumPy Array
arr = np.array(l)

print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2
(3, 3)


import numpy as np

# 2D Python List
l = [[1,2,3],
     [4,5,6],
     [7,8,9]]

print(l)

# Convert into NumPy Array
arr = np.array(l)

print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)

In [86]:
import numpy as np

# 3D Python List
l = [
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
]

print("Python List:")
print(l)

# Convert to NumPy Array
arr = np.array(l)

print("\nNumPy Array:")
print(arr)

print("\nDimensions :", arr.ndim)
print("Shape      :", arr.shape)
print("Size       :", arr.size)
print("Data Type  :", arr.dtype)

Python List:
[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

NumPy Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Dimensions : 3
Shape      : (2, 2, 3)
Size       : 12
Data Type  : int64


In [90]:
l = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
print(l)

#3D array
arr = np.array(l)
print(arr)
print('dimensions',arr.ndim)

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
dimensions 3
